#!/bin/bash

go run cmd/main.go $@

if [ ! -f tailwindcss-linux-x64 ]; then
    wget https://github.com/tailwindlabs/tailwindcss/releases/download/v4.0.12/tailwindcss-linux-x64
    sudo chmod +x tailwindcss-linux-x64
fi

./tailwindcss-linux-x64 \
  -i main.css \
  -o out/assets/styles.css \
  --minify
