version: "3"

tasks:
  default:
    cmds:
      - go run cmd/main.go {{.CLI_ARGS}}
    silent: true

  dev:
    deps:
      - log:build
      - log:serve

  log:build:
    cmds:
      - go run cmd/main.go build
    silent: true

  log:serve:
    cmds:
      - npx serve out/
    silent: true

  build:
    cmds:
      - go build -o bin/glowx cmd/main.go
    silent: true
